### ISSUE TITLE
Install tips?

### ISSUE THREAD

**Issue by killerbonzai** [kronenthaler/plex-subscene#11]
I must be doing something wrong..
I have the plugin installed and I have it checked in my settings - agents in both movies and tv-shows..
Yet I don't seem to be getting any kind of subtitles from subscene..

At first I thought the .bundle went straight in to the Program Files > Plex server > Plugins but since it didnt show up in the agents I then put it in my Users > AppData > Local > Plex server > Plugins folder..
It shows up in my agents settings but it doesn't seem to work.. :(

I had the opensubtitles.org agent running 'fine' before that.. 'fine' as in it didn't always seem to download the correct files and then I went looking for a better agent..

Where did I fuck up? Sry if this is the wrong place to post this.. couldn't find a better place..

**Comment by kronenthaler** [comment]
What you mention sounds correct. Although there might be some factors related to that:
1. Maybe the languages you are picking are not finding any matches on subscene.com
2. Most likely, subscene.com changed something on its HTML and the plugin is currently failing. I will take a look at my logs to see if that's the case. Keep an eye on this repo in case i post a solution in the coming days.
